#!/usr/bin/python3

# Ale Cominotti - 2020

from resources import CodeGenerator
import time
import random
import os
import argparse
import base64
import re
import webbrowser

# Vars -----
PURPLE = '\033[95m'
CYAN = '\033[96m'     
DARKCYAN = '\033[36m'
BLUE = '\033[94m'
GREEN = '\033[92m'
YELLOW = '\033[93m'
RED = '\033[91m'
BOLD = '\033[1m'
ITALIC = '\033[3m'
WHITE = '\033[0m'   
minRandom=0 #default min
maxRandom=5 #default max
resourcesFolder="resources/"
txtfile="hydraCode.txt"
hydraURL="https://hydra.ojack.xyz/?code="
#hydraURL = hydraURL.encode("utf-8")
web=False

def printBanner():
    os.system("clear")
    print(YELLOW + """  _   _           _              ____          _         ____                           _             
 | | | |_   _  __| |_ __ __ _   / ___|___   __| | ___   / ___| ___ _ __   ___ _ __ __ _| |_ ___  _ __ 
 | |_| | | | |/ _` | '__/ _` | | |   / _ \ / _` |/ _ \ | |  _ / _ \ '_ \ / _ \ '__/ _` | __/ _ \| '__|
 |  _  | |_| | (_| | | | (_| | | |__| (_) | (_| |  __/ | |_| |  __/ | | |  __/ | | (_| | || (_) | |   
 |_| |_|\__, |\__,_|_|  \__,_|  \____\___/ \__,_|\___|  \____|\___|_| |_|\___|_|  \__,_|\__\___/|_|   
        |___/
                """ + WHITE)

def showInfo():
    printBanner()
    helptxt=open(resourcesFolder + "help.txt", 'r').read()
    print(helptxt)

#Argument parsing -----
parser = argparse.ArgumentParser()
parser.add_argument("-f", "--function", type=int, metavar='<Integer>', help="Constantamount of functions (Always the same)")
parser.add_argument("--min", type=int, metavar='<Integer>', help="Minimum amount of functions")
parser.add_argument("--max", type=int, metavar='<Integer>', help="Maximum amount of functions")
parser.add_argument("--web", action='store_true', help="Open hydra in web browser with generated code")
parser.add_argument("-i", "--info", action='store_true', help="Shows information")
args = parser.parse_args()

if args.info:
    showInfo()
    exit(0)
if args.function:
    minRandom=args.function
    maxRandom=args.function
else:
    if args.min:
        minRandom=args.min
        if(minRandom>maxRandom):
            maxRandom=minRandom
    if args.max:
        maxRandom=args.max
    if args.min and args.max and (args.min>args.max):
        print(RED+"ERROR: " + WHITE + "Max value must be bigger than Min value")
        exit(1)
if args.web:
    web=True
   


def generateCode(hydra, functionsAmount):
    fullCode="" # hydra code to generate URL
    info="// Random Hydra code generated by HCG: https://github.com/alecominotti/hydracodegenerator\n// @alecominotti\n\n"
    if args.function:
        print(WHITE+"Functions amount: " + str(functionsAmount) + " (Constant)")
    else:
        print(WHITE+"Functions amount: Random between " + str(minRandom) + "-" + str(maxRandom), end="")
        if (not args.function) and (not args.min) and (not args.max):
            print(" (Default)")
        else:
            print()
    terminalSize = os.popen('stty size', 'r').read().split()
    bar=""
    for z in range(int(terminalSize[1])):
        bar+="-"
    print(CYAN + bar + WHITE)
    with open(txtfile, 'w+') as txt:
        txt.write(info)
        fullCode+="""{info}""".format(info=info)
        source = hydra.genSource()
        txt.write(source + "\n")
        fullCode+="""{source}\n""".format(source=source)
        print(GREEN + source)        
        for x in range(functionsAmount):
            func = hydra.genFunction()
            txt.write('  ' + func + "\n")
            fullCode+="""  {func}\n""".format(func=func)
            print("  " + func)
        txt.write(".out(o0)")
        fullCode += ".out(o0)"
        print(".out(o0)")
    print(CYAN + bar + WHITE)    
    fullCode = base64.b64encode(fullCode.encode("UTF-8")).decode("ascii")
    finalURL = hydraURL + fullCode 
    return(str(finalURL))


def main():
    hydra=CodeGenerator.CodeGenerator()
    functionsAmount= random.randint(minRandom,maxRandom)
    printBanner()
    hydraCodeURL = generateCode(hydra, functionsAmount)
    print(WHITE+"Select code and press " + GREEN + "Ctrl+Shift+C " + WHITE + "to copy it")
    print(WHITE+"Press " + GREEN + "Enter " + WHITE + "to generate new code")
    print(WHITE+"Code is saved in '" + GREEN + "hydraCode.txt" + WHITE + "'")
    print(WHITE+"\nOpen the following link to run Hydra with this code:")
    print(BLUE+hydraCodeURL)
    print(WHITE)
    if web:
        webbrowser.open_new(hydraCodeURL)
    input("Press " + GREEN + "Ctrl+C " + WHITE + "to exit")
   

try:
    while True:    
        main()        
except KeyboardInterrupt:
        print(YELLOW + "\nProcess stopped." + WHITE)